#Browser to use: chrome, firefox, edge
browser=chrome

# Base URL of the application
homepage_url = https://firetms.com/de
# Implicit wait time in seconds
implicitWait=10



# Credentials for login
username=paveljankuloski@gmail.com
password=Drvo123456

